
-- Griho Sheba database schema (PostgreSQL)
-- Mirrors the JPA entities in backend/model.
-- Customer and Admin are NOT separate tables: every account (customer,
-- worker, admin) lives in `users`, distinguished by the `role` column.
-- This matches how User.java / AuthController.java are actually implemented.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    email           VARCHAR(150),
    phone           VARCHAR(20) UNIQUE,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER', -- CUSTOMER, WORKER, ADMIN
    dob             VARCHAR(20),
    specialty       VARCHAR(100),
    experience      VARCHAR(50),
    nid             VARCHAR(50),
    photo_url       TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',  -- PENDING, APPROVED, REJECTED
    approved        BOOLEAN NOT NULL DEFAULT FALSE
);

-- DomesticWorker (backend/model/DomesticWorker.java) is a supplementary
-- table for worker-only attributes, keyed 1:1 to a users.id row where
-- role = 'WORKER'. Name/specialty/experience/rating shown to customers
-- come from `users`; this table adds verification + availability state.
CREATE TABLE workers (
    worker_id       BIGINT PRIMARY KEY REFERENCES users(id),
    nid_number      VARCHAR(50) UNIQUE,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    is_available    BOOLEAN NOT NULL DEFAULT TRUE,
    rating          DOUBLE PRECISION DEFAULT 0.00
);

CREATE TABLE services (
    service_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name    VARCHAR(100) NOT NULL,
    category        VARCHAR(100),
    base_price      DOUBLE PRECISION
);

CREATE TABLE bookings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id       BIGINT REFERENCES workers(worker_id),
    worker_name     VARCHAR(150),
    customer_name   VARCHAR(150),
    customer_phone  VARCHAR(20),
    service_date    DATE,
    comment         VARCHAR(1000),
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING' -- PENDING, CONFIRMED, COMPLETED, CANCELLED
);

CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT NOT NULL REFERENCES bookings(id),
    amount          DOUBLE PRECISION NOT NULL,
    method          VARCHAR(20), -- BKASH, NAGAD, CARD, CASH
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    paid_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE complaints (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT REFERENCES bookings(id),
    worker_name     VARCHAR(150),
    customer_name   VARCHAR(150),
    customer_phone  VARCHAR(20),
    complaint       VARCHAR(2000),
    status          VARCHAR(20) NOT NULL DEFAULT 'OPEN', -- OPEN, UNDER_REVIEW, RESOLVED, DISMISSED
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reviews (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id      BIGINT REFERENCES bookings(id),
    worker_id       BIGINT REFERENCES workers(worker_id),
    customer_phone  VARCHAR(20),
    rating          INTEGER CHECK (rating BETWEEN 1 AND 5),
    comment         VARCHAR(1000),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_bookings_customer_phone ON bookings(customer_phone);
CREATE INDEX idx_bookings_worker_id ON bookings(worker_id);
CREATE INDEX idx_users_role_status ON users(role, status);
